import type { Borrower, PortfolioStats } from './types';

export const portfolioStats: PortfolioStats = {
  totalBorrowers: 1250,
  riskDistribution: {
    low: 950,
    moderate: 225,
    high: 75,
  },
  newlyFlagged: 12,
  riskTrend: [
    { month: 'Jan', low: 980, moderate: 200, high: 70 },
    { month: 'Feb', low: 970, moderate: 210, high: 70 },
    { month: 'Mar', low: 965, moderate: 215, high: 70 },
    { month: 'Apr', low: 960, moderate: 220, high: 70 },
    { month: 'May', low: 955, moderate: 220, high: 75 },
    { month: 'Jun', low: 950, moderate: 225, high: 75 },
  ],
  riskComparison: [
    { name: 'Portfolio Avg.', behavioral: 68, financial: 75 },
    { name: 'Industry Avg.', behavioral: 65, financial: 78 },
  ],
};

const conversations: Borrower['conversations'] = [
  {
    id: 'conv1',
    date: '2024-06-15',
    type: 'Call',
    customer: 'Alice Johnson',
    banker: 'John Doe',
    transcript: "Banker: Hi Alice, just checking in on the new equipment financing. Customer: Oh, hi. Yeah, um, it's... it's going. We've had some, uh, unexpected... well, things are just a bit tight right now. It's probably nothing.",
    behavioralCues: ['Hesitation / uncertainty', 'Vague language'],
    riskIndicator: 'Moderate',
  },
  {
    id: 'conv2',
    date: '2024-05-20',
    type: 'Email',
    customer: 'Alice Johnson',
    banker: 'John Doe',
    transcript: 'Subject: Re: Q2 Financials. Hi John, Apologies for the delay. We are finalizing the numbers and will send them over as soon as possible. We had to divert some funds to cover an unforeseen maintenance issue, which is why the cash flow looks a little different this quarter. Everything is under control. Best, Alice',
    behavioralCues: ['Excessive justification', 'Delay in providing financials'],
    riskIndicator: 'Moderate',
  },
  {
    id: 'conv3',
    date: '2024-04-10',
    type: 'Chat',
    customer: 'Alice Johnson',
    banker: 'John Doe',
    transcript: 'Banker: Hi Alice, can we schedule a time to discuss your Q2 outlook? Customer: Not a good time right now, very busy. Can we do this next month? Banker: It will only take 15 minutes. Customer: I really can\'t. Talk later.',
    behavioralCues: ['Avoidance of financial topics', 'Reduced engagement'],
    riskIndicator: 'High',
  },
];


export const borrowers: Borrower[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    borrowerId: 'BID-84321',
    loan: { amount: 250000, tenure: 60, type: 'Equipment Financing' },
    repaymentStatus: 'On Track',
    traditionalCreditScore: 720,
    aiCognitiveRisk: {
      score: 82,
      classification: 'High',
      confidence: 0.91,
      trend: 'Deteriorating',
      changeFromPrevious: 15,
    },
    behavioralDrivers: ['Financial Stress Signals', 'Avoidance Behavior', 'Increased Uncertainty'],
    linguisticSignals: ['Use of tentative language', 'Topic shifting away from financials', 'Delayed responses'],
    conversations,
    geography: 'North America',
    segment: 'Manufacturing',
    rmName: 'John Doe',
  },
  {
    id: '2',
    name: 'Bob Williams',
    borrowerId: 'BID-84322',
    loan: { amount: 500000, tenure: 120, type: 'Commercial Real Estate' },
    repaymentStatus: 'On Track',
    traditionalCreditScore: 780,
    aiCognitiveRisk: {
      score: 45,
      classification: 'Moderate',
      confidence: 0.85,
      trend: 'Stable',
      changeFromPrevious: 2,
    },
    behavioralDrivers: ['Slight increase in payment justification', 'Seasonal cash flow concerns'],
    linguisticSignals: ['Mentions of "tight margins"', 'Reassurance seeking'],
    conversations: [conversations[0]],
    geography: 'Europe',
    segment: 'Retail',
    rmName: 'Jane Smith',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    borrowerId: 'BID-84323',
    loan: { amount: 75000, tenure: 36, type: 'Working Capital' },
    repaymentStatus: 'On Track',
    traditionalCreditScore: 810,
    aiCognitiveRisk: {
      score: 15,
      classification: 'Low',
      confidence: 0.98,
      trend: 'Improving',
      changeFromPrevious: -5,
    },
    behavioralDrivers: ['Positive business outlook', 'Proactive communication'],
    linguisticSignals: ['Confident language', 'Future growth discussion'],
    conversations: [],
    geography: 'North America',
    segment: 'Technology',
    rmName: 'John Doe',
  },
  {
    id: '4',
    name: 'Diana Miller',
    borrowerId: 'BID-84324',
    loan: { amount: 120000, tenure: 48, type: 'Business Expansion' },
    repaymentStatus: 'On Track',
    traditionalCreditScore: 750,
    aiCognitiveRisk: {
      score: 30,
      classification: 'Low',
      confidence: 0.95,
      trend: 'Stable',
      changeFromPrevious: 0,
    },
    behavioralDrivers: ['Consistent payment history', 'Clear financial reporting'],
    linguisticSignals: ['Formal and direct communication'],
    conversations: [],
    geography: 'Asia',
    segment: 'Services',
    rmName: 'Emily White',
  },
  {
    id: '5',
    name: 'Ethan Jones',
    borrowerId: 'BID-84325',
    loan: { amount: 300000, tenure: 84, type: 'Asset Purchase' },
    repaymentStatus: 'Delayed',
    traditionalCreditScore: 680,
    aiCognitiveRisk: {
      score: 75,
      classification: 'High',
      confidence: 0.88,
      trend: 'Deteriorating',
      changeFromPrevious: 10,
    },
    behavioralDrivers: ['Missed payment deadlines', 'Negative sentiment'],
    linguisticSignals: ['Expressions of frustration', 'Blaming external factors'],
    conversations: [conversations[1], conversations[2]],
    geography: 'Europe',
    segment: 'Logistics',
    rmName: 'Jane Smith',
  },
];
